name: Build Packages

on:
  push:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache pacman packages
      id: cache-pacman
      uses: actions/cache@v4
      with:
        path: pkg
        key: ${{ runner.os }}-pacman-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pacman-

    - name: Pull Docker image
      run: docker pull archlinux
      
    - name: Run builder
      run: |
        docker run --rm --privileged -v $PWD/out:/out -v $PWD/pkg:/var/cache/pacman/pkg archlinux sh -c "
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm base-devel git
          useradd -m builder
          echo 'builder ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/01_builder
          git clone --depth 1 https://github.com/LingmoOS-Testing/lingmo-arch-pkgbuilder /builder
          chown -R builder /builder
          sudo -u builder sh -c 'cd /builder && ./build.sh'
          cp /builder/outputs/* /out
        "

    - name: List packages
      run: |
        du -sh out
        ls -lh out

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        compression-level: 0
        path: ./out/*

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Pull Docker image
        run: docker pull archlinux

      - name: Build repository
        run: |
          docker run --rm -v $PWD/packages:/repo archlinux sh -c "
            repo-add /repo/lingmo.db.tar.gz /repo/*.pkg.tar.zst
          "

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
