name: Build Packages

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:latest
    steps:
    - name: Cache pacman packages
      id: cache-pacman
      uses: actions/cache@v4
      with:
        path: /var/cache/pacman/pkg
        key: ${{ runner.os }}-pacman-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pacman-

    - name: Set up build environment
      run: |
        pacman-key --init
        pacman-key --populate archlinux
        pacman -Syu --noconfirm base-devel git
        useradd -m builder
        echo 'builder ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
        sudo -u builder git clone --depth 1 https://github.com/LingmoOS/archlingmo-pkg /tmp/archlingmo-pkg
   
    - name: Build Packages
      run: sudo -u builder sh -c 'cd /tmp/archlingmo-pkg/packages && ./build.sh'

    - name: List packages
      run: du -ch /tmp/archlingmo-pkg/packages/outputs/*

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: x86_64
        compression-level: 0
        path: /tmp/archlingmo-pkg/packages/outputs/*

  upload:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ~/repo

      - name: Install pacman
        run: sudo apt update && sudo apt install pacman-package-manager libarchive-tools

      - name: Build repository
        run: |
          cp -r --update ~/repo/* .
          ls -lah
          ls -lah x86_64
          pwd
          for i in $(ls);do
            [ -d $i ] && repo-add $i/lingmo.db.tar.gz $i/*.pkg.tar.zst
          done

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update: $(date --rfc-3339=seconds)"
          git push
